{
 "title": "air_quality_monitor_demo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "testing",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "metrics", "query": { "query": "metrics(air_quality)" } },
   {
    "name": "station",
    "label": "station",
    "query": {
     "query": "label_values($metrics, station_id)"
    }
   },
   {
    "name": "name_of_metrics",
    "label": "圖表",
    "query": "Temperature (˚C) : air_quality_temperature_celsius,Humidity (%) : air_quality_humidity_percentage,PM2.5 (µg/m³) : air_quality_pm25_microgram_cubic_meter,PM10 (µg/m³) : air_quality_pm10_microgram_cubic_meter,CO2 (ppm) : air_quality_co2_ppm,CO (ppm) : air_quality_co_ppm,HC (ppb) : air_quality_hc_ppb,O3 (ppb) : air_quality_o3_ppb,VOC (ppb) : air_quality_voc_ppb"
   },
   {
    "name": "name_of_station",
    "label": "測站 左",
    "query": "活動中心B1 : B1F,共同教育大樓106教室 : 106,地質環境館屋頂 : ARF,化生實驗室左側 : PL,化生實驗室右側 : PR,Unknown 1 : A1F,Unknown 2 : M"
   },
   {
    "name": "name_of_station_2",
    "label": "測站 右",
    "query": "活動中心B1 : B1F,共同教育大樓106教室 : 106,地質環境館屋頂 : ARF,化生實驗室左側 : PL,化生實驗室右側 : PR,Unknown 1 : A1F,Unknown 2 : M"
   },
   {
    "name": "compare_metrics",
    "label": "比較測站",
    "query": "活動中心B1 : B1F,共同教育大樓106教室 : 106,地質環境館屋頂 : ARF,化生實驗室左側 : PL,化生實驗室右側 : PR,Unknown 1 : A1F,Unknown 2 : M"
   },
   { "name": "url", "label": "url", "query": "140.123.101.199:3000" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"css-1ntvj01\" style=\"display: flex; align-items: center; justify-content: center; height: 100px;\">\r\n    <h3 class=\"css-p584vf\" style=\"text-align: center; font-size: 40px; color:#99d3e8\">${name_of_station:text}</h3>\r\n</div>\r\n\r\n\r\n <!-- background: linear-gradient(120deg, rgb(12, 26, 73), rgb(19, 68, 117)); -->"
   }
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "options": {
    "content": "<div class=\"css-1ntvj01\" style=\"display: flex; align-items: center; justify-content: center; height: 100px;\">\r\n    <h3 class=\"css-p584vf\" style=\"text-align: center; font-size: 40px;\">${name_of_metrics:text}</h3>\r\n</div>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<div class=\"css-1ntvj01\" style=\"display: flex; align-items: center; justify-content: center; height: 100px;\">\r\n    <h3 class=\"css-p584vf\" style=\"text-align: center; font-size: 40px; color:rgb(227, 145, 199)\">${name_of_station_2:text}</h3>\r\n</div>\r\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_temperature_celsius{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_aqi{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "chose \"name_of_station\" and \"name_of_metrics\" above",
   "gridPos": { "h": 16, "w": 10, "x": 7, "y": 3 },
   "targets": [
    {
     "expr": "$name_of_metrics{station_id=\"$name_of_station\"}",
     "legendFormat": "{{station_id}}_1_${name_of_metrics:text}"
    },
    {
     "expr": "$name_of_metrics{station_id=\"$name_of_station_2\"}",
     "legendFormat": "{{station_id}}_2_${name_of_metrics:text}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_aqi{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_temperature_celsius{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_humidity_percentage{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_humidity_percentage{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_pm25_microgram_cubic_meter{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_pm25_microgram_cubic_meter{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_pm10_microgram_cubic_meter{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_pm10_microgram_cubic_meter{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert",
   "type": "alertlist",
   "description": "grouped by 站點. alert condition is shown in label.",
   "gridPos": { "h": 22, "w": 10, "x": 7, "y": 19 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_co2_ppm{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_co2_ppm{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_co_ppm{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_co_ppm{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_hc_ppb{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_hc_ppb{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_o3_ppb{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_o3_ppb{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_voc_ppb{station_id=\"$name_of_station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_voc_ppb{station_id=\"$name_of_station_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "嘉義市空品監測站", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "環境部嘉義測站影像",
   "type": "text",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 42 },
   "options": {
    "content": "<img src=\"http://140.123.101.199:33625/get_image\" />"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_prediction_pm25_microgram_cubic_meter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "air_quality_prediction_pm25_microgram_cubic_meter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_prediction_pm25_microgram_cubic_meter",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "air_quality_temperature_celsius{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "air_quality_humidity_percentage{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PM2.5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "air_quality_pm25_microgram_cubic_meter{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PM10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "air_quality_pm10_microgram_cubic_meter{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CO2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "air_quality_co2_ppm{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "CO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "air_quality_co_ppm{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "HC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "air_quality_hc_ppb{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "O3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "O3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "air_quality_o3_ppb{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "VOC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "air_quality_voc_ppb{station_id=~\"$compare_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}